server:
  port: 9527
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      default-Zone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    instance:
      instance-id: zuul9527.com
      prefer-ip-adrress: true

info:
  app.name: hyy-springcloud
  company.name:
zuul:
  routes:
    mydept.sererId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept #不能使用这个路径访问
  prefix: /hyy  #设置公共的前缀
